version: '3'
services:
  backend:
    build: ./backend
    tty: true
    volumes:
      - "./backend:/backend"
    working_dir: "/backend"
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
  frontend:
    build: ./frontend
    tty: true
    volumes:
      - "./frontend:/frontend"
    working_dir: "/frontend"
    ports:
      - "4200:4200"
    command: "node"
    # ng serve --host 0.0.0.0 --port 3010

