version: '3'
services:
  backend:
    build: ./backend
    tty: true
    volumes:
      - "./backend:/backend"
    working_dir: "/backend"
    ports:
      - "3000:3000"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
  frontend:
    build: ./frontend
    tty: true
    volumes:
      - "./frontend:/frontend"
    working_dir: "/frontend"
    ports:
      - "4200:4200"
    command: "node"
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8081:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - ./backend/swagger/openapi.yml:/openapi.yml
    environment:
      SWAGGER_JSON: /openapi.yml
  swagger-api:
    image: danielgtaylor/apisprout
    container_name: "swagger-api"
    ports:
      - "8083:8000"
    volumes:
      - ./backend/swagger/openapi.yml:/openapi.yml
    command: /openapi.yml
    networks:
      swagger_link:
        aliases:
          - local.swagger.apisprout
  swagger-nginx:
    image: nginx:mainline-alpine
    container_name: "swagger-nginx"
    ports:
      - "8084:8084"
    volumes:
      - ./backend/swagger/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      swagger_link:
        aliases:
          - local.swagger.api
networks:
  swagger_link:
    external: true
